// Sinh bởi scripts/build-fonts.py — đừng sửa tay.
export type VnFontGroup = 'sans' | 'serif' | 'script' | 'display'

export const VN_FONTS: { id: string; label: string; group: VnFontGroup }[] = [
  { id: "vn-1k-reey", label: "1K Reey", group: 'script' },
  { id: "vn-acumin-pro", label: "Acumin Pro", group: 'sans' },
  { id: "vn-agu-display", label: "Agu Display", group: 'sans' },
  { id: "vn-allura", label: "Allura", group: 'script' },
  { id: "vn-anek-latin", label: "Anek Latin", group: 'sans' },
  { id: "vn-anybody", label: "Anybody", group: 'sans' },
  { id: "vn-birthstone-bounce", label: "Birthstone Bounce", group: 'script' },
  { id: "vn-dancing-script", label: "Dancing Script", group: 'display' },
  { id: "vn-dfvn-bagel-fat-one", label: "DFVN Bagel Fat One", group: 'display' },
  { id: "vn-dfvn-rubra-costa", label: "DFVN Rubra Costa", group: 'script' },
  { id: "vn-dongle", label: "Dongle", group: 'display' },
  { id: "vn-dvn-a-dong-bladerunner", label: "DVN - A DONG - BLADERUNNER", group: 'display' },
  { id: "vn-dvn-autography", label: "DVN - Autography", group: 'script' },
  { id: "vn-dvn-bakbak-one", label: "DVN - Bakbak One", group: 'sans' },
  { id: "vn-dvn-cinzel-decorative", label: "DVN - Cinzel Decorative", group: 'serif' },
  { id: "vn-dvn-colus", label: "DVN - Colus", group: 'display' },
  { id: "vn-dvn-dune-rise", label: "DVN - Dune Rise", group: 'display' },
  { id: "vn-dvn-fat", label: "DVN - Fat", group: 'display' },
  { id: "vn-dvn-loveya-script", label: "DVN - Loveya Script", group: 'script' },
  { id: "vn-dvn-milkshake", label: "DVN - Milkshake", group: 'script' },
  { id: "vn-dvn-north-land", label: "DVN - North Land", group: 'sans' },
  { id: "vn-dvn-parasi", label: "DVN - Parasi", group: 'serif' },
  { id: "vn-dvn-photograph", label: "DVN - Photograph", group: 'script' },
  { id: "vn-dvn-poetsen-one", label: "DVN - Poetsen One", group: 'display' },
  { id: "vn-dvn-praise", label: "DVN - Praise", group: 'script' },
  { id: "vn-dvn-retrowarp", label: "DVN - RetroWarp", group: 'serif' },
  { id: "vn-dvn-tahu", label: "DVN - Tahu!", group: 'script' },
  { id: "vn-dvn-uefa-euro", label: "DVN - UEFA Euro", group: 'sans' },
  { id: "vn-eb-garamond", label: "EB Garamond", group: 'serif' },
  { id: "vn-ephesis", label: "Ephesis", group: 'script' },
  { id: "vn-fahkwang", label: "Fahkwang", group: 'sans' },
  { id: "vn-fraunces", label: "Fraunces", group: 'serif' },
  { id: "vn-fz-fzshitiansongs-cloud", label: "Fz FZShiTianSongS Cloud", group: 'display' },
  { id: "vn-geist", label: "Geist", group: 'sans' },
  { id: "vn-google-sans-flex-9pt", label: "Google Sans Flex 9pt", group: 'sans' },
  { id: "vn-harmonyos-sans", label: "HarmonyOS Sans", group: 'sans' },
  { id: "vn-helvetica", label: "Helvetica", group: 'sans' },
  { id: "vn-hp-dns-gibsons-one", label: "HP DNS Gibsons One", group: 'display' },
  { id: "vn-iciel-lovestory", label: "iCiel Lovestory", group: 'script' },
  { id: "vn-kd-hidayatullah", label: "KD Hidayatullah", group: 'sans' },
  { id: "vn-lexend", label: "Lexend", group: 'sans' },
  { id: "vn-lnth-awesome-south-korea", label: "LNTH-Awesome South Korea", group: 'display' },
  { id: "vn-lnth-blackoninaut-bold-brk", label: "LNTH-Blackoninaut Bold BRK", group: 'serif' },
  { id: "vn-lnth-blobby-chug", label: "LNTH-BLOBBY CHUG", group: 'display' },
  { id: "vn-lnth-ceria-lebaran", label: "LNTH-Ceria Lebaran", group: 'sans' },
  { id: "vn-lnth-christmas-in-brighton", label: "LNTH-Christmas in Brighton", group: 'script' },
  { id: "vn-lnth-deborstel", label: "LNTH-DeBorstel", group: 'script' },
  { id: "vn-lnth-getcoffee", label: "LNTH-GetCoffee", group: 'script' },
  { id: "vn-lnth-hotel-lorint", label: "LNTH-Hotel Lorint", group: 'script' },
  { id: "vn-lnth-kids-chinese-font", label: "LNTH-Kids Chinese Font", group: 'display' },
  { id: "vn-lnth-manis-banget", label: "LNTH-Manis Banget", group: 'script' },
  { id: "vn-lnth-ralline", label: "LNTH-Ralline", group: 'script' },
  { id: "vn-lnth-sugiono", label: "LNTH-Sugiono", group: 'script' },
  { id: "vn-lnth-sweet-hazel", label: "LNTH-Sweet Hazel", group: 'script' },
  { id: "vn-lnth-symphonie-cat", label: "LNTH-Symphonie CAT", group: 'display' },
  { id: "vn-lnth-water-dragon", label: "LNTH-Water Dragon", group: 'display' },
  { id: "vn-lnthfc-balinos", label: "LNTHFC-Balinos", group: 'script' },
  { id: "vn-manrope", label: "Manrope", group: 'sans' },
  { id: "vn-meow-script", label: "Meow Script", group: 'script' },
  { id: "vn-merienda", label: "Merienda", group: 'script' },
  { id: "vn-milestone-script", label: "Milestone Script", group: 'script' },
  { id: "vn-montserrat", label: "Montserrat", group: 'sans' },
  { id: "vn-mtd-antro-vectra", label: "MTD Antro Vectra", group: 'script' },
  { id: "vn-mtd-barakah", label: "MTD Barakah", group: 'display' },
  { id: "vn-mtd-hummington", label: "MTD Hummington", group: 'script' },
  { id: "vn-mtd-st-friska", label: "MTD St Friska", group: 'display' },
  { id: "vn-nata-sans", label: "Nata Sans", group: 'sans' },
  { id: "vn-oswald", label: "Oswald", group: 'sans' },
  { id: "vn-pacifico", label: "Pacifico", group: 'script' },
  { id: "vn-paris-2024", label: "Paris 2024", group: 'display' },
  { id: "vn-philosopher", label: "Philosopher", group: 'sans' },
  { id: "vn-playfair-display", label: "Playfair Display", group: 'serif' },
  { id: "vn-prata", label: "Prata", group: 'sans' },
  { id: "vn-protest-strike", label: "Protest Strike", group: 'sans' },
  { id: "vn-ps-anton", label: "PS Anton", group: 'sans' },
  { id: "vn-ps-bigger", label: "PS Bigger", group: 'sans' },
  { id: "vn-ps-bolden", label: "PS Bolden", group: 'sans' },
  { id: "vn-questrial", label: "Questrial", group: 'sans' },
  { id: "vn-raleway", label: "Raleway", group: 'sans' },
  { id: "vn-saira", label: "Saira", group: 'sans' },
  { id: "vn-the-nautigal", label: "The Nautigal", group: 'script' },
  { id: "vn-tnh-xuong", label: "TNH Xuong", group: 'display' },
  { id: "vn-ubuntu", label: "Ubuntu", group: 'sans' },
  { id: "vn-vl-angelline", label: "VL Angelline", group: 'script' },
  { id: "vn-vl-selfie", label: "VL Selfie", group: 'script' },
  { id: "vn-wind-script", label: "Wind Script", group: 'script' },
  { id: "vn-young", label: "Young", group: 'sans' },
  { id: "vn-young-display", label: "Young Display", group: 'sans' },
]
