// Sinh bởi scripts/build-fonts.py — đừng sửa tay.
export type VnFontGroup = 'sans' | 'serif' | 'script' | 'display'

export const VN_FONTS: { id: string; label: string; group: VnFontGroup }[] = [
  { id: "vn-1k-reey", label: "1K Reey", group: 'script' },
  { id: "vn-acumin-pro", label: "Acumin Pro", group: 'sans' },
  { id: "vn-agu-display", label: "Agu Display", group: 'sans' },
  { id: "vn-ahsing", label: "Ahsing", group: 'display' },
  { id: "vn-akbaal", label: "Akbaal", group: 'serif' },
  { id: "vn-alkatra", label: "Alkatra", group: 'sans' },
  { id: "vn-allura", label: "Allura", group: 'script' },
  { id: "vn-amigh", label: "Amigh", group: 'serif' },
  { id: "vn-amoresa", label: "Amoresa", group: 'script' },
  { id: "vn-anek-latin", label: "Anek Latin", group: 'sans' },
  { id: "vn-aniyah", label: "Aniyah", group: 'script' },
  { id: "vn-anybody", label: "Anybody", group: 'sans' },
  { id: "vn-aquiline-two", label: "Aquiline Two", group: 'script' },
  { id: "vn-archer", label: "Archer", group: 'serif' },
  { id: "vn-aretha-bridge", label: "Aretha Bridge", group: 'display' },
  { id: "vn-argue", label: "Argue", group: 'serif' },
  { id: "vn-austyns-sakyra", label: "Austyns Sakyra", group: 'serif' },
  { id: "vn-avalen-rekas", label: "Avalen Rekas", group: 'display' },
  { id: "vn-avinga", label: "Avinga", group: 'serif' },
  { id: "vn-axel", label: "Axel", group: 'sans' },
  { id: "vn-bd-streetsign-sans", label: "BD StreetSign Sans", group: 'sans' },
  { id: "vn-belanosima", label: "Belanosima", group: 'sans' },
  { id: "vn-berishye", label: "Berishye", group: 'script' },
  { id: "vn-bi", label: "Bi", group: 'sans' },
  { id: "vn-bing-boss", label: "Bing Boss", group: 'display' },
  { id: "vn-birthstone-bounce", label: "Birthstone Bounce", group: 'script' },
  { id: "vn-bolgifam-script", label: "Bolgifam Script", group: 'script' },
  { id: "vn-brainstroke", label: "Brainstroke", group: 'sans' },
  { id: "vn-bridget", label: "Bridget", group: 'serif' },
  { id: "vn-brotherhood-script", label: "Brotherhood Script", group: 'script' },
  { id: "vn-brutal-font-pro", label: "Brutal Font Pro", group: 'display' },
  { id: "vn-bt-danta", label: "BT Danta", group: 'sans' },
  { id: "vn-budge", label: "Budge", group: 'display' },
  { id: "vn-cadet", label: "Cadet", group: 'sans' },
  { id: "vn-catherine", label: "Catherine", group: 'display' },
  { id: "vn-cezanne", label: "CEZANNE", group: 'display' },
  { id: "vn-chabul", label: "CHABUL", group: 'display' },
  { id: "vn-chalkcoal", label: "Chalkcoal", group: 'sans' },
  { id: "vn-cheese-milky", label: "Cheese Milky", group: 'sans' },
  { id: "vn-cherry-blossom", label: "Cherry Blossom", group: 'sans' },
  { id: "vn-christmas-fecsival", label: "Christmas Fecsival", group: 'display' },
  { id: "vn-cinnamon", label: "Cinnamon", group: 'sans' },
  { id: "vn-curve-retro", label: "Curve Retro", group: 'display' },
  { id: "vn-cutline", label: "Cutline", group: 'sans' },
  { id: "vn-cyrene", label: "Cyrene", group: 'sans' },
  { id: "vn-dancing-script", label: "Dancing Script", group: 'display' },
  { id: "vn-dfvn-bagel-fat-one", label: "DFVN Bagel Fat One", group: 'display' },
  { id: "vn-dfvn-rubra-costa", label: "DFVN Rubra Costa", group: 'script' },
  { id: "vn-didoska", label: "Didoska", group: 'script' },
  { id: "vn-discoteca-rounded", label: "Discoteca Rounded", group: 'sans' },
  { id: "vn-distant-stroke", label: "Distant Stroke", group: 'script' },
  { id: "vn-dongle", label: "Dongle", group: 'display' },
  { id: "vn-dt-phudu", label: "DT Phudu", group: 'sans' },
  { id: "vn-dvn-a-dong-bladerunner", label: "DVN - A DONG - BLADERUNNER", group: 'display' },
  { id: "vn-dvn-autography", label: "DVN - Autography", group: 'script' },
  { id: "vn-dvn-bakbak-one", label: "DVN - Bakbak One", group: 'sans' },
  { id: "vn-dvn-cinzel-decorative", label: "DVN - Cinzel Decorative", group: 'serif' },
  { id: "vn-dvn-colus", label: "DVN - Colus", group: 'display' },
  { id: "vn-dvn-dune-rise", label: "DVN - Dune Rise", group: 'display' },
  { id: "vn-dvn-fat", label: "DVN - Fat", group: 'display' },
  { id: "vn-dvn-loveya-script", label: "DVN - Loveya Script", group: 'script' },
  { id: "vn-dvn-milkshake", label: "DVN - Milkshake", group: 'script' },
  { id: "vn-dvn-north-land", label: "DVN - North Land", group: 'sans' },
  { id: "vn-dvn-parasi", label: "DVN - Parasi", group: 'serif' },
  { id: "vn-dvn-photograph", label: "DVN - Photograph", group: 'script' },
  { id: "vn-dvn-poetsen-one", label: "DVN - Poetsen One", group: 'display' },
  { id: "vn-dvn-praise", label: "DVN - Praise", group: 'script' },
  { id: "vn-dvn-retrowarp", label: "DVN - RetroWarp", group: 'serif' },
  { id: "vn-dvn-tahu", label: "DVN - Tahu!", group: 'script' },
  { id: "vn-dvn-uefa-euro", label: "DVN - UEFA Euro", group: 'sans' },
  { id: "vn-eb-garamond", label: "EB Garamond", group: 'serif' },
  { id: "vn-ed-aughris", label: "ED Aughris", group: 'sans' },
  { id: "vn-ephesis", label: "Ephesis", group: 'script' },
  { id: "vn-fagibestin", label: "Fagibestin", group: 'script' },
  { id: "vn-fahkwang", label: "Fahkwang", group: 'sans' },
  { id: "vn-feinlag", label: "Feinlag", group: 'display' },
  { id: "vn-finura", label: "Finura", group: 'serif' },
  { id: "vn-fraunces", label: "Fraunces", group: 'serif' },
  { id: "vn-french-kiss", label: "French Kiss", group: 'script' },
  { id: "vn-fz-fzshitiansongs-cloud", label: "Fz FZShiTianSongS Cloud", group: 'display' },
  { id: "vn-galiano-text", label: "Galiano Text", group: 'script' },
  { id: "vn-geist", label: "Geist", group: 'sans' },
  { id: "vn-geizer", label: "Geizer", group: 'display' },
  { id: "vn-gelato-fresco", label: "Gelato Fresco", group: 'script' },
  { id: "vn-glifta", label: "Glifta", group: 'serif' },
  { id: "vn-glitzier", label: "Glitzier", group: 'script' },
  { id: "vn-google-sans-flex-9pt", label: "Google Sans Flex 9pt", group: 'sans' },
  { id: "vn-gosha-sans", label: "Gosha Sans", group: 'sans' },
  { id: "vn-graffiti-classic", label: "Graffiti Classic", group: 'display' },
  { id: "vn-h-h-samuel", label: "H.H. Samuel", group: 'sans' },
  { id: "vn-harmonyos-sans", label: "HarmonyOS Sans", group: 'sans' },
  { id: "vn-hatter-display-pro", label: "Hatter Display Pro", group: 'serif' },
  { id: "vn-hatton", label: "Hatton", group: 'serif' },
  { id: "vn-helenita-dos", label: "Helenita Dos", group: 'sans' },
  { id: "vn-helvetica", label: "Helvetica", group: 'sans' },
  { id: "vn-hey-comic", label: "Hey Comic", group: 'display' },
  { id: "vn-hi-barbie", label: "Hi Barbie", group: 'script' },
  { id: "vn-histogram", label: "Histogram", group: 'script' },
  { id: "vn-hit-the-road", label: "Hit The Road", group: 'sans' },
  { id: "vn-hoshiko-satsuki", label: "Hoshiko Satsuki", group: 'script' },
  { id: "vn-hp-dns-gibsons-one", label: "HP DNS Gibsons One", group: 'display' },
  { id: "vn-huggie-bunny", label: "Huggie Bunny", group: 'display' },
  { id: "vn-hy-aleold", label: "HY-Aleold", group: 'display' },
  { id: "vn-hy-aleold-2", label: "HY-Aleold (2)", group: 'serif' },
  { id: "vn-hy-allipt", label: "HY-Allipt", group: 'script' },
  { id: "vn-hy-allist", label: "HY-Allist", group: 'serif' },
  { id: "vn-i-f-c-los-banditos", label: "I.F.C. LOS BANDITOS", group: 'sans' },
  { id: "vn-iciel-alina", label: "iCiel Alina", group: 'script' },
  { id: "vn-iciel-amerigraf", label: "iCiel Amerigraf", group: 'display' },
  { id: "vn-iciel-andes-rounded", label: "iCiel Andes Rounded", group: 'sans' },
  { id: "vn-iciel-bambola", label: "iCiel Bambola", group: 'script' },
  { id: "vn-iciel-lovestory", label: "iCiel Lovestory", group: 'script' },
  { id: "vn-icielbc-ddchardwarerough", label: "iCielBC DDCHardwareRough", group: 'display' },
  { id: "vn-jambie", label: "Jambie", group: 'script' },
  { id: "vn-jasmineupc", label: "JasmineUPC", group: 'sans' },
  { id: "vn-jnr-sb-font", label: "JNR-SB-Font", group: 'sans' },
  { id: "vn-kd-hidayatullah", label: "KD Hidayatullah", group: 'sans' },
  { id: "vn-lagona", label: "Lagona", group: 'serif' },
  { id: "vn-lexend", label: "Lexend", group: 'sans' },
  { id: "vn-lf-klaristha", label: "lf Klaristha", group: 'serif' },
  { id: "vn-lf-tisk", label: "LF tisk", group: 'display' },
  { id: "vn-lnth-awesome-south-korea", label: "LNTH-Awesome South Korea", group: 'display' },
  { id: "vn-lnth-blackoninaut-bold-brk", label: "LNTH-Blackoninaut Bold BRK", group: 'serif' },
  { id: "vn-lnth-blobby-chug", label: "LNTH-BLOBBY CHUG", group: 'display' },
  { id: "vn-lnth-ceria-lebaran", label: "LNTH-Ceria Lebaran", group: 'sans' },
  { id: "vn-lnth-christmas-in-brighton", label: "LNTH-Christmas in Brighton", group: 'script' },
  { id: "vn-lnth-deborstel", label: "LNTH-DeBorstel", group: 'script' },
  { id: "vn-lnth-getcoffee", label: "LNTH-GetCoffee", group: 'script' },
  { id: "vn-lnth-hotel-lorint", label: "LNTH-Hotel Lorint", group: 'script' },
  { id: "vn-lnth-kids-chinese-font", label: "LNTH-Kids Chinese Font", group: 'display' },
  { id: "vn-lnth-manis-banget", label: "LNTH-Manis Banget", group: 'script' },
  { id: "vn-lnth-ralline", label: "LNTH-Ralline", group: 'script' },
  { id: "vn-lnth-sugiono", label: "LNTH-Sugiono", group: 'script' },
  { id: "vn-lnth-sweet-hazel", label: "LNTH-Sweet Hazel", group: 'script' },
  { id: "vn-lnth-symphonie-cat", label: "LNTH-Symphonie CAT", group: 'display' },
  { id: "vn-lnth-water-dragon", label: "LNTH-Water Dragon", group: 'display' },
  { id: "vn-lnthfc-balinos", label: "LNTHFC-Balinos", group: 'script' },
  { id: "vn-louise", label: "Louise", group: 'script' },
  { id: "vn-loyola-pro", label: "Loyola Pro", group: 'sans' },
  { id: "vn-luna-morta-mystical", label: "Luna Morta Mystical", group: 'display' },
  { id: "vn-mackin", label: "Mackin", group: 'display' },
  { id: "vn-magic-school-one", label: "Magic School One", group: 'display' },
  { id: "vn-maison-neue", label: "Maison Neue", group: 'sans' },
  { id: "vn-manrope", label: "Manrope", group: 'sans' },
  { id: "vn-masmuseh", label: "Masmuseh", group: 'script' },
  { id: "vn-megivia-italic", label: "Megivia Italic", group: 'script' },
  { id: "vn-meow-script", label: "Meow Script", group: 'script' },
  { id: "vn-merienda", label: "Merienda", group: 'script' },
  { id: "vn-migra", label: "Migra", group: 'serif' },
  { id: "vn-mileast", label: "Mileast", group: 'serif' },
  { id: "vn-milestone-script", label: "Milestone Script", group: 'script' },
  { id: "vn-milven", label: "Milven", group: 'serif' },
  { id: "vn-minecraft-ten", label: "Minecraft Ten", group: 'display' },
  { id: "vn-mithella", label: "Mithella", group: 'sans' },
  { id: "vn-monarda", label: "Monarda", group: 'script' },
  { id: "vn-montserrat", label: "Montserrat", group: 'sans' },
  { id: "vn-mtd-antro-vectra", label: "MTD Antro Vectra", group: 'script' },
  { id: "vn-mtd-barakah", label: "MTD Barakah", group: 'display' },
  { id: "vn-mtd-hummington", label: "MTD Hummington", group: 'script' },
  { id: "vn-mtd-st-friska", label: "MTD St Friska", group: 'display' },
  { id: "vn-nata-sans", label: "Nata Sans", group: 'sans' },
  { id: "vn-negrita-pro", label: "Negrita Pro", group: 'sans' },
  { id: "vn-neofolia", label: "Neofolia", group: 'display' },
  { id: "vn-nghich-thuy-han", label: "Nghich Thuy Han", group: 'sans' },
  { id: "vn-nova-square", label: "Nova Square", group: 'sans' },
  { id: "vn-oregano", label: "Oregano", group: 'script' },
  { id: "vn-oswald", label: "Oswald", group: 'sans' },
  { id: "vn-pacifico", label: "Pacifico", group: 'script' },
  { id: "vn-palm-canyon-drive", label: "Palm Canyon Drive", group: 'script' },
  { id: "vn-paris-2024", label: "Paris 2024", group: 'display' },
  { id: "vn-philosopher", label: "Philosopher", group: 'sans' },
  { id: "vn-playfair-display", label: "Playfair Display", group: 'serif' },
  { id: "vn-playful", label: "Playful", group: 'sans' },
  { id: "vn-plumage", label: "Plumage", group: 'script' },
  { id: "vn-prata", label: "Prata", group: 'sans' },
  { id: "vn-protest-strike", label: "Protest Strike", group: 'sans' },
  { id: "vn-providence", label: "Providence", group: 'script' },
  { id: "vn-ps-anton", label: "PS Anton", group: 'sans' },
  { id: "vn-ps-bebas-neue", label: "PS Bebas Neue", group: 'sans' },
  { id: "vn-ps-big-shoulders", label: "PS Big Shoulders", group: 'sans' },
  { id: "vn-ps-bigger", label: "PS Bigger", group: 'sans' },
  { id: "vn-ps-bolden", label: "PS Bolden", group: 'sans' },
  { id: "vn-queen-of-silence", label: "Queen of Silence", group: 'display' },
  { id: "vn-questrial", label: "Questrial", group: 'sans' },
  { id: "vn-raleway", label: "Raleway", group: 'sans' },
  { id: "vn-rancho", label: "Rancho", group: 'script' },
  { id: "vn-reggae-one", label: "Reggae One", group: 'display' },
  { id: "vn-rochester", label: "Rochester", group: 'script' },
  { id: "vn-rose-gard", label: "Rose Gard", group: 'display' },
  { id: "vn-runholdy", label: "Runholdy", group: 'display' },
  { id: "vn-saga-arjuna", label: "Saga Arjuna", group: 'display' },
  { id: "vn-saira", label: "Saira", group: 'sans' },
  { id: "vn-sandraloka", label: "Sandraloka", group: 'sans' },
  { id: "vn-satisfy", label: "Satisfy", group: 'script' },
  { id: "vn-scaver", label: "Scaver", group: 'serif' },
  { id: "vn-shantay", label: "Shantay", group: 'script' },
  { id: "vn-smile-delight", label: "Smile Delight", group: 'display' },
  { id: "vn-sounds-analog", label: "Sounds Analog", group: 'display' },
  { id: "vn-splendid-script", label: "Splendid Script", group: 'script' },
  { id: "vn-stager", label: "Stager", group: 'serif' },
  { id: "vn-stardew-valley", label: "Stardew Valley", group: 'display' },
  { id: "vn-storm-fighter", label: "Storm Fighter", group: 'display' },
  { id: "vn-streetbrush", label: "Streetbrush", group: 'script' },
  { id: "vn-sue-ellen-francisco", label: "Sue Ellen Francisco", group: 'script' },
  { id: "vn-sweet-peachy", label: "Sweet Peachy", group: 'sans' },
  { id: "vn-symphony-pro", label: "Symphony Pro", group: 'script' },
  { id: "vn-tan-jambore", label: "TAN Jambore", group: 'sans' },
  { id: "vn-thang", label: "Thang", group: 'script' },
  { id: "vn-the-nautigal", label: "The Nautigal", group: 'script' },
  { id: "vn-thegora", label: "Thegora", group: 'sans' },
  { id: "vn-tnh-xuong", label: "TNH Xuong", group: 'display' },
  { id: "vn-tratexvit", label: "TratexVit", group: 'sans' },
  { id: "vn-ubuntu", label: "Ubuntu", group: 'sans' },
  { id: "vn-verlag", label: "Verlag", group: 'sans' },
  { id: "vn-vermin-verile", label: "Vermin Verile", group: 'display' },
  { id: "vn-vintage-goods", label: "Vintage Goods", group: 'script' },
  { id: "vn-virlyn", label: "Virlyn", group: 'display' },
  { id: "vn-viva-la-fiesta-uno-base", label: "Viva La Fiesta - Uno Base", group: 'display' },
  { id: "vn-vl-angelline", label: "VL Angelline", group: 'script' },
  { id: "vn-vl-selfie", label: "VL Selfie", group: 'script' },
  { id: "vn-vnm-sans-std", label: "VNM Sans Std", group: 'sans' },
  { id: "vn-wind-script", label: "Wind Script", group: 'script' },
  { id: "vn-winstgue", label: "Winstgue", group: 'display' },
  { id: "vn-young", label: "Young", group: 'sans' },
  { id: "vn-young-display", label: "Young Display", group: 'sans' },
]
