// Sinh bởi scripts/build-fonts.py — đừng sửa tay.
export type VnFontGroup = 'sans' | 'serif' | 'script' | 'display'
export type VnFontLang = 'vi' | 'ja' | 'ko'

export const VN_FONTS: { id: string; label: string; group: VnFontGroup; lang: VnFontLang }[] = [
  { id: "vn-1ftv-nakana", label: "1FTV Nakana", group: 'sans', lang: 'vi' },
  { id: "vn-1ftv-ranoya", label: "1FTV Ranoya", group: 'display', lang: 'vi' },
  { id: "vn-1k-reey", label: "1K Reey", group: 'script', lang: 'vi' },
  { id: "vn-acumin-pro", label: "Acumin Pro", group: 'sans', lang: 'vi' },
  { id: "vn-agu-display", label: "Agu Display", group: 'sans', lang: 'vi' },
  { id: "vn-ahsing", label: "Ahsing", group: 'display', lang: 'vi' },
  { id: "vn-akbaal", label: "Akbaal", group: 'serif', lang: 'vi' },
  { id: "vn-alkatra", label: "Alkatra", group: 'sans', lang: 'vi' },
  { id: "vn-allura", label: "Allura", group: 'script', lang: 'vi' },
  { id: "vn-amigh", label: "Amigh", group: 'serif', lang: 'vi' },
  { id: "vn-amoresa", label: "Amoresa", group: 'script', lang: 'vi' },
  { id: "vn-anek-latin", label: "Anek Latin", group: 'sans', lang: 'vi' },
  { id: "vn-aniyah", label: "Aniyah", group: 'script', lang: 'vi' },
  { id: "vn-anybody", label: "Anybody", group: 'sans', lang: 'vi' },
  { id: "ja-aoboshi-one", label: "Aoboshi One", group: 'serif', lang: 'ja' },
  { id: "vn-aquiline-two", label: "Aquiline Two", group: 'script', lang: 'vi' },
  { id: "vn-archer", label: "Archer", group: 'serif', lang: 'vi' },
  { id: "vn-aretha-bridge", label: "Aretha Bridge", group: 'display', lang: 'vi' },
  { id: "vn-argue", label: "Argue", group: 'serif', lang: 'vi' },
  { id: "ko-asta-sans", label: "Asta Sans", group: 'sans', lang: 'ko' },
  { id: "vn-austyns-sakyra", label: "Austyns Sakyra", group: 'serif', lang: 'vi' },
  { id: "vn-avalen-rekas", label: "Avalen Rekas", group: 'display', lang: 'vi' },
  { id: "vn-avinga", label: "Avinga", group: 'serif', lang: 'vi' },
  { id: "vn-axel", label: "Axel", group: 'sans', lang: 'vi' },
  { id: "ko-bagel-fat-one", label: "Bagel Fat One", group: 'display', lang: 'ko' },
  { id: "vn-bd-streetsign-sans", label: "BD StreetSign Sans", group: 'sans', lang: 'vi' },
  { id: "vn-belanosima", label: "Belanosima", group: 'sans', lang: 'vi' },
  { id: "vn-berishye", label: "Berishye", group: 'script', lang: 'vi' },
  { id: "vn-bi", label: "Bi", group: 'sans', lang: 'vi' },
  { id: "vn-bing-boss", label: "Bing Boss", group: 'display', lang: 'vi' },
  { id: "vn-birthstone-bounce", label: "Birthstone Bounce", group: 'script', lang: 'vi' },
  { id: "ja-biz-udgothic", label: "BIZ UDGothic", group: 'sans', lang: 'ja' },
  { id: "ja-biz-udmincho", label: "BIZ UDMincho", group: 'serif', lang: 'ja' },
  { id: "ja-biz-udpgothic", label: "BIZ UDPGothic", group: 'sans', lang: 'ja' },
  { id: "ja-biz-udpmincho", label: "BIZ UDPMincho", group: 'serif', lang: 'ja' },
  { id: "ko-black-and-white-picture", label: "Black And White Picture", group: 'display', lang: 'ko' },
  { id: "ko-black-han-sans", label: "Black Han Sans", group: 'sans', lang: 'ko' },
  { id: "vn-bolgifam-script", label: "Bolgifam Script", group: 'script', lang: 'vi' },
  { id: "vn-brainstroke", label: "Brainstroke", group: 'sans', lang: 'vi' },
  { id: "vn-bridget", label: "Bridget", group: 'serif', lang: 'vi' },
  { id: "vn-brotherhood-script", label: "Brotherhood Script", group: 'script', lang: 'vi' },
  { id: "vn-brutal-font-pro", label: "Brutal Font Pro", group: 'display', lang: 'vi' },
  { id: "vn-bt-danta", label: "BT Danta", group: 'sans', lang: 'vi' },
  { id: "vn-budge", label: "Budge", group: 'display', lang: 'vi' },
  { id: "vn-cadet", label: "Cadet", group: 'sans', lang: 'vi' },
  { id: "vn-catherine", label: "Catherine", group: 'display', lang: 'vi' },
  { id: "vn-cezanne", label: "CEZANNE", group: 'display', lang: 'vi' },
  { id: "vn-chabul", label: "CHABUL", group: 'display', lang: 'vi' },
  { id: "vn-chalkcoal", label: "Chalkcoal", group: 'sans', lang: 'vi' },
  { id: "vn-cheese-milky", label: "Cheese Milky", group: 'sans', lang: 'vi' },
  { id: "vn-cherry-blossom", label: "Cherry Blossom", group: 'sans', lang: 'vi' },
  { id: "ja-cherry-bomb-one", label: "Cherry Bomb One", group: 'display', lang: 'ja' },
  { id: "ja-chokokutai", label: "Chokokutai", group: 'display', lang: 'ja' },
  { id: "vn-christmas-fecsival", label: "Christmas Fecsival", group: 'display', lang: 'vi' },
  { id: "vn-cinnamon", label: "Cinnamon", group: 'sans', lang: 'vi' },
  { id: "vn-curve-retro", label: "Curve Retro", group: 'display', lang: 'vi' },
  { id: "ko-cute-font", label: "Cute Font", group: 'display', lang: 'ko' },
  { id: "vn-cutline", label: "Cutline", group: 'sans', lang: 'vi' },
  { id: "vn-cyrene", label: "Cyrene", group: 'sans', lang: 'vi' },
  { id: "vn-dancing-script", label: "Dancing Script", group: 'display', lang: 'vi' },
  { id: "ja-darumadrop-one", label: "Darumadrop One", group: 'display', lang: 'ja' },
  { id: "ja-dela-gothic-one", label: "Dela Gothic One", group: 'display', lang: 'ja' },
  { id: "vn-dfvn-bagel-fat-one", label: "DFVN Bagel Fat One", group: 'display', lang: 'vi' },
  { id: "vn-dfvn-berfilem", label: "DFVN Berfilem", group: 'serif', lang: 'vi' },
  { id: "vn-dfvn-ghelisyah", label: "DFVN Ghelisyah", group: 'display', lang: 'vi' },
  { id: "vn-dfvn-indulge-script", label: "DFVN Indulge Script", group: 'script', lang: 'vi' },
  { id: "vn-dfvn-mbf-space-habitat", label: "DFVN MBF Space Habitat", group: 'display', lang: 'vi' },
  { id: "vn-dfvn-radja-lover", label: "DFVN Radja Lover", group: 'script', lang: 'vi' },
  { id: "vn-dfvn-rubra-costa", label: "DFVN Rubra Costa", group: 'script', lang: 'vi' },
  { id: "vn-dfvn-stampa-v1", label: "DFVN STAMPA V1", group: 'display', lang: 'vi' },
  { id: "vn-didoska", label: "Didoska", group: 'script', lang: 'vi' },
  { id: "ko-diphylleia", label: "Diphylleia", group: 'serif', lang: 'ko' },
  { id: "vn-discoteca-rounded", label: "Discoteca Rounded", group: 'sans', lang: 'vi' },
  { id: "vn-distant-stroke", label: "Distant Stroke", group: 'script', lang: 'vi' },
  { id: "vn-dl-calvera", label: "DL Calvera", group: 'display', lang: 'vi' },
  { id: "ko-do-hyeon", label: "Do Hyeon", group: 'sans', lang: 'ko' },
  { id: "ko-dokdo", label: "Dokdo", group: 'display', lang: 'ko' },
  { id: "vn-dongle", label: "Dongle", group: 'display', lang: 'vi' },
  { id: "ko-dongle", label: "Dongle", group: 'sans', lang: 'ko' },
  { id: "ja-dotgothic16", label: "DotGothic16", group: 'sans', lang: 'ja' },
  { id: "vn-dt-phudu", label: "DT Phudu", group: 'sans', lang: 'vi' },
  { id: "vn-dvn-a-dong-bladerunner", label: "DVN - A DONG - BLADERUNNER", group: 'display', lang: 'vi' },
  { id: "vn-dvn-autography", label: "DVN - Autography", group: 'script', lang: 'vi' },
  { id: "vn-dvn-bakbak-one", label: "DVN - Bakbak One", group: 'sans', lang: 'vi' },
  { id: "vn-dvn-cinzel-decorative", label: "DVN - Cinzel Decorative", group: 'serif', lang: 'vi' },
  { id: "vn-dvn-colus", label: "DVN - Colus", group: 'display', lang: 'vi' },
  { id: "vn-dvn-dune-rise", label: "DVN - Dune Rise", group: 'display', lang: 'vi' },
  { id: "vn-dvn-fat", label: "DVN - Fat", group: 'display', lang: 'vi' },
  { id: "vn-dvn-loveya-script", label: "DVN - Loveya Script", group: 'script', lang: 'vi' },
  { id: "vn-dvn-milkshake", label: "DVN - Milkshake", group: 'script', lang: 'vi' },
  { id: "vn-dvn-north-land", label: "DVN - North Land", group: 'sans', lang: 'vi' },
  { id: "vn-dvn-parasi", label: "DVN - Parasi", group: 'serif', lang: 'vi' },
  { id: "vn-dvn-photograph", label: "DVN - Photograph", group: 'script', lang: 'vi' },
  { id: "vn-dvn-poetsen-one", label: "DVN - Poetsen One", group: 'display', lang: 'vi' },
  { id: "vn-dvn-praise", label: "DVN - Praise", group: 'script', lang: 'vi' },
  { id: "vn-dvn-retrowarp", label: "DVN - RetroWarp", group: 'serif', lang: 'vi' },
  { id: "vn-dvn-tahu", label: "DVN - Tahu!", group: 'script', lang: 'vi' },
  { id: "vn-dvn-uefa-euro", label: "DVN - UEFA Euro", group: 'sans', lang: 'vi' },
  { id: "ko-east-sea-dokdo", label: "East Sea Dokdo", group: 'script', lang: 'ko' },
  { id: "vn-eb-garamond", label: "EB Garamond", group: 'serif', lang: 'vi' },
  { id: "vn-ed-aughris", label: "ED Aughris", group: 'sans', lang: 'vi' },
  { id: "vn-ephesis", label: "Ephesis", group: 'script', lang: 'vi' },
  { id: "vn-fagibestin", label: "Fagibestin", group: 'script', lang: 'vi' },
  { id: "vn-fahkwang", label: "Fahkwang", group: 'sans', lang: 'vi' },
  { id: "vn-feinlag", label: "Feinlag", group: 'display', lang: 'vi' },
  { id: "vn-finura", label: "Finura", group: 'serif', lang: 'vi' },
  { id: "vn-fraunces", label: "Fraunces", group: 'serif', lang: 'vi' },
  { id: "vn-french-kiss", label: "French Kiss", group: 'script', lang: 'vi' },
  { id: "vn-fz-fzshitiansongs-cloud", label: "Fz FZShiTianSongS Cloud", group: 'display', lang: 'vi' },
  { id: "ko-gaegu", label: "Gaegu", group: 'script', lang: 'ko' },
  { id: "vn-galiano-text", label: "Galiano Text", group: 'script', lang: 'vi' },
  { id: "ko-gamja-flower", label: "Gamja Flower", group: 'script', lang: 'ko' },
  { id: "ko-gasoek-one", label: "Gasoek One", group: 'sans', lang: 'ko' },
  { id: "vn-geist", label: "Geist", group: 'sans', lang: 'vi' },
  { id: "vn-geizer", label: "Geizer", group: 'display', lang: 'vi' },
  { id: "vn-gelato-fresco", label: "Gelato Fresco", group: 'script', lang: 'vi' },
  { id: "vn-glifta", label: "Glifta", group: 'serif', lang: 'vi' },
  { id: "vn-glitzier", label: "Glitzier", group: 'script', lang: 'vi' },
  { id: "vn-google-sans-flex-9pt", label: "Google Sans Flex 9pt", group: 'sans', lang: 'vi' },
  { id: "vn-gosha-sans", label: "Gosha Sans", group: 'sans', lang: 'vi' },
  { id: "ko-gothic-a1", label: "Gothic A1", group: 'sans', lang: 'ko' },
  { id: "ko-gowun-batang", label: "Gowun Batang", group: 'serif', lang: 'ko' },
  { id: "ko-gowun-dodum", label: "Gowun Dodum", group: 'sans', lang: 'ko' },
  { id: "vn-graffiti-classic", label: "Graffiti Classic", group: 'display', lang: 'vi' },
  { id: "ko-grandiflora-one", label: "Grandiflora One", group: 'serif', lang: 'ko' },
  { id: "ko-gugi", label: "Gugi", group: 'display', lang: 'ko' },
  { id: "vn-h-h-samuel", label: "H.H. Samuel", group: 'sans', lang: 'vi' },
  { id: "ja-hachi-maru-pop", label: "Hachi Maru Pop", group: 'script', lang: 'ja' },
  { id: "ko-hahmlet", label: "Hahmlet", group: 'serif', lang: 'ko' },
  { id: "vn-harmonyos-sans", label: "HarmonyOS Sans", group: 'sans', lang: 'vi' },
  { id: "vn-hatter-display-pro", label: "Hatter Display Pro", group: 'serif', lang: 'vi' },
  { id: "vn-hatton", label: "Hatton", group: 'serif', lang: 'vi' },
  { id: "vn-helenita-dos", label: "Helenita Dos", group: 'sans', lang: 'vi' },
  { id: "vn-helvetica", label: "Helvetica", group: 'sans', lang: 'vi' },
  { id: "vn-hey-comic", label: "Hey Comic", group: 'display', lang: 'vi' },
  { id: "vn-hi-barbie", label: "Hi Barbie", group: 'script', lang: 'vi' },
  { id: "ko-hi-melody", label: "Hi Melody", group: 'script', lang: 'ko' },
  { id: "ja-hina-mincho", label: "Hina Mincho", group: 'serif', lang: 'ja' },
  { id: "vn-histogram", label: "Histogram", group: 'script', lang: 'vi' },
  { id: "vn-hit-the-road", label: "Hit The Road", group: 'sans', lang: 'vi' },
  { id: "vn-hoshiko-satsuki", label: "Hoshiko Satsuki", group: 'script', lang: 'vi' },
  { id: "vn-hp-dns-gibsons-one", label: "HP DNS Gibsons One", group: 'display', lang: 'vi' },
  { id: "vn-huggie-bunny", label: "Huggie Bunny", group: 'display', lang: 'vi' },
  { id: "vn-hy-aaript", label: "HY-Aaript", group: 'script', lang: 'vi' },
  { id: "vn-hy-abrace", label: "HY-Abrace", group: 'serif', lang: 'vi' },
  { id: "vn-hy-agolar", label: "HY-Agolar", group: 'serif', lang: 'vi' },
  { id: "vn-hy-agolic", label: "HY-Agolic", group: 'display', lang: 'vi' },
  { id: "vn-hy-aguack", label: "HY-Aguack", group: 'sans', lang: 'vi' },
  { id: "vn-hy-agular", label: "HY-Agular", group: 'sans', lang: 'vi' },
  { id: "vn-hy-aguold", label: "HY-Aguold", group: 'sans', lang: 'vi' },
  { id: "vn-hy-aleght", label: "HY-Aleght", group: 'serif', lang: 'vi' },
  { id: "vn-hy-alelar-2", label: "HY-Alelar (2)", group: 'serif', lang: 'vi' },
  { id: "vn-hy-alelic-3", label: "HY-Alelic(3)", group: 'serif', lang: 'vi' },
  { id: "vn-hy-aleold", label: "HY-Aleold", group: 'display', lang: 'vi' },
  { id: "vn-hy-aleold-2", label: "HY-Aleold (2)", group: 'serif', lang: 'vi' },
  { id: "vn-hy-allipt", label: "HY-Allipt", group: 'script', lang: 'vi' },
  { id: "vn-hy-allist", label: "HY-Allist", group: 'serif', lang: 'vi' },
  { id: "vn-hy-cherga", label: "HY-Cherga", group: 'display', lang: 'vi' },
  { id: "vn-hy-chirie", label: "HY-Chirie", group: 'display', lang: 'vi' },
  { id: "vn-hy-ilyas", label: "HY-Ilyas", group: 'script', lang: 'vi' },
  { id: "vn-i-f-c-los-banditos", label: "I.F.C. LOS BANDITOS", group: 'sans', lang: 'vi' },
  { id: "ja-ibm-plex-sans-jp", label: "IBM Plex Sans JP", group: 'sans', lang: 'ja' },
  { id: "ko-ibm-plex-sans-kr", label: "IBM Plex Sans KR", group: 'sans', lang: 'ko' },
  { id: "vn-iciel-alina", label: "iCiel Alina", group: 'script', lang: 'vi' },
  { id: "vn-iciel-amerigraf", label: "iCiel Amerigraf", group: 'display', lang: 'vi' },
  { id: "vn-iciel-andes-rounded", label: "iCiel Andes Rounded", group: 'sans', lang: 'vi' },
  { id: "vn-iciel-bambola", label: "iCiel Bambola", group: 'script', lang: 'vi' },
  { id: "vn-iciel-lovestory", label: "iCiel Lovestory", group: 'script', lang: 'vi' },
  { id: "vn-iciel-soup-of-justice", label: "iCiel Soup of Justice", group: 'display', lang: 'vi' },
  { id: "vn-icielbc-ddchardwarerough", label: "iCielBC DDCHardwareRough", group: 'display', lang: 'vi' },
  { id: "vn-jambie", label: "Jambie", group: 'script', lang: 'vi' },
  { id: "vn-jasmineupc", label: "JasmineUPC", group: 'sans', lang: 'vi' },
  { id: "vn-jnr-sb-font", label: "JNR-SB-Font", group: 'sans', lang: 'vi' },
  { id: "ko-jua", label: "Jua", group: 'sans', lang: 'ko' },
  { id: "ja-kaisei-decol", label: "Kaisei Decol", group: 'serif', lang: 'ja' },
  { id: "ja-kaisei-harunoumi", label: "Kaisei HarunoUmi", group: 'serif', lang: 'ja' },
  { id: "ja-kaisei-opti", label: "Kaisei Opti", group: 'serif', lang: 'ja' },
  { id: "ja-kaisei-tokumin", label: "Kaisei Tokumin", group: 'serif', lang: 'ja' },
  { id: "ja-kapakana", label: "Kapakana", group: 'script', lang: 'ja' },
  { id: "vn-kd-hidayatullah", label: "KD Hidayatullah", group: 'sans', lang: 'vi' },
  { id: "ko-kirang-haerang", label: "Kirang Haerang", group: 'display', lang: 'ko' },
  { id: "ja-kiwi-maru", label: "Kiwi Maru", group: 'serif', lang: 'ja' },
  { id: "ja-klee-one", label: "Klee One", group: 'script', lang: 'ja' },
  { id: "ja-kosugi", label: "Kosugi", group: 'sans', lang: 'ja' },
  { id: "ja-kosugi-maru", label: "Kosugi Maru", group: 'sans', lang: 'ja' },
  { id: "vn-lagona", label: "Lagona", group: 'serif', lang: 'vi' },
  { id: "vn-lexend", label: "Lexend", group: 'sans', lang: 'vi' },
  { id: "vn-lf-klaristha", label: "lf Klaristha", group: 'serif', lang: 'vi' },
  { id: "vn-lf-tisk", label: "LF tisk", group: 'display', lang: 'vi' },
  { id: "ja-line-seed-jp", label: "LINE Seed JP", group: 'sans', lang: 'ja' },
  { id: "vn-lnth-awesome-south-korea", label: "LNTH-Awesome South Korea", group: 'display', lang: 'vi' },
  { id: "vn-lnth-blackoninaut-bold-brk", label: "LNTH-Blackoninaut Bold BRK", group: 'serif', lang: 'vi' },
  { id: "vn-lnth-blobby-chug", label: "LNTH-BLOBBY CHUG", group: 'display', lang: 'vi' },
  { id: "vn-lnth-ceria-lebaran", label: "LNTH-Ceria Lebaran", group: 'sans', lang: 'vi' },
  { id: "vn-lnth-christmas-in-brighton", label: "LNTH-Christmas in Brighton", group: 'script', lang: 'vi' },
  { id: "vn-lnth-deborstel", label: "LNTH-DeBorstel", group: 'script', lang: 'vi' },
  { id: "vn-lnth-getcoffee", label: "LNTH-GetCoffee", group: 'script', lang: 'vi' },
  { id: "vn-lnth-hotel-lorint", label: "LNTH-Hotel Lorint", group: 'script', lang: 'vi' },
  { id: "vn-lnth-kids-chinese-font", label: "LNTH-Kids Chinese Font", group: 'display', lang: 'vi' },
  { id: "vn-lnth-manis-banget", label: "LNTH-Manis Banget", group: 'script', lang: 'vi' },
  { id: "vn-lnth-ralline", label: "LNTH-Ralline", group: 'script', lang: 'vi' },
  { id: "vn-lnth-sugiono", label: "LNTH-Sugiono", group: 'script', lang: 'vi' },
  { id: "vn-lnth-sweet-hazel", label: "LNTH-Sweet Hazel", group: 'script', lang: 'vi' },
  { id: "vn-lnth-symphonie-cat", label: "LNTH-Symphonie CAT", group: 'display', lang: 'vi' },
  { id: "vn-lnth-water-dragon", label: "LNTH-Water Dragon", group: 'display', lang: 'vi' },
  { id: "vn-lnthfc-balinos", label: "LNTHFC-Balinos", group: 'script', lang: 'vi' },
  { id: "vn-louise", label: "Louise", group: 'script', lang: 'vi' },
  { id: "vn-loyola-pro", label: "Loyola Pro", group: 'sans', lang: 'vi' },
  { id: "vn-luna-morta-mystical", label: "Luna Morta Mystical", group: 'display', lang: 'vi' },
  { id: "ja-m-plus-1", label: "M PLUS 1", group: 'sans', lang: 'ja' },
  { id: "ja-m-plus-1-code", label: "M PLUS 1 Code", group: 'sans', lang: 'ja' },
  { id: "ja-m-plus-1p", label: "M PLUS 1p", group: 'sans', lang: 'ja' },
  { id: "ja-m-plus-2", label: "M PLUS 2", group: 'sans', lang: 'ja' },
  { id: "ja-m-plus-rounded-1c", label: "M PLUS Rounded 1c", group: 'sans', lang: 'ja' },
  { id: "ja-m-plus-u", label: "M PLUS U", group: 'sans', lang: 'ja' },
  { id: "vn-mackin", label: "Mackin", group: 'display', lang: 'vi' },
  { id: "vn-magic-school-one", label: "Magic School One", group: 'display', lang: 'vi' },
  { id: "vn-maison-neue", label: "Maison Neue", group: 'sans', lang: 'vi' },
  { id: "vn-manrope", label: "Manrope", group: 'sans', lang: 'vi' },
  { id: "vn-masmuseh", label: "Masmuseh", group: 'script', lang: 'vi' },
  { id: "vn-megivia-italic", label: "Megivia Italic", group: 'script', lang: 'vi' },
  { id: "vn-meow-script", label: "Meow Script", group: 'script', lang: 'vi' },
  { id: "vn-merienda", label: "Merienda", group: 'script', lang: 'vi' },
  { id: "vn-migra", label: "Migra", group: 'serif', lang: 'vi' },
  { id: "vn-mileast", label: "Mileast", group: 'serif', lang: 'vi' },
  { id: "vn-milestone-script", label: "Milestone Script", group: 'script', lang: 'vi' },
  { id: "vn-milven", label: "Milven", group: 'serif', lang: 'vi' },
  { id: "vn-minecraft-ten", label: "Minecraft Ten", group: 'display', lang: 'vi' },
  { id: "vn-mithella", label: "Mithella", group: 'sans', lang: 'vi' },
  { id: "ja-mochiy-pop-one", label: "Mochiy Pop One", group: 'sans', lang: 'ja' },
  { id: "ja-mochiy-pop-p-one", label: "Mochiy Pop P One", group: 'sans', lang: 'ja' },
  { id: "ko-moirai-one", label: "Moirai One", group: 'display', lang: 'ko' },
  { id: "vn-monarda", label: "Monarda", group: 'script', lang: 'vi' },
  { id: "ja-monomaniac-one", label: "Monomaniac One", group: 'sans', lang: 'ja' },
  { id: "vn-montserrat", label: "Montserrat", group: 'sans', lang: 'vi' },
  { id: "vn-mtd-antro-vectra", label: "MTD Antro Vectra", group: 'script', lang: 'vi' },
  { id: "vn-mtd-barakah", label: "MTD Barakah", group: 'display', lang: 'vi' },
  { id: "vn-mtd-hummington", label: "MTD Hummington", group: 'script', lang: 'vi' },
  { id: "vn-mtd-st-friska", label: "MTD St Friska", group: 'display', lang: 'vi' },
  { id: "ja-murecho", label: "Murecho", group: 'sans', lang: 'ja' },
  { id: "ko-nanum-brush-script", label: "Nanum Brush Script", group: 'script', lang: 'ko' },
  { id: "ko-nanum-gothic", label: "Nanum Gothic", group: 'sans', lang: 'ko' },
  { id: "ko-nanum-gothic-coding", label: "Nanum Gothic Coding", group: 'script', lang: 'ko' },
  { id: "ko-nanum-myeongjo", label: "Nanum Myeongjo", group: 'serif', lang: 'ko' },
  { id: "ko-nanum-pen-script", label: "Nanum Pen Script", group: 'script', lang: 'ko' },
  { id: "vn-nata-sans", label: "Nata Sans", group: 'sans', lang: 'vi' },
  { id: "vn-negrita-pro", label: "Negrita Pro", group: 'sans', lang: 'vi' },
  { id: "vn-neofolia", label: "Neofolia", group: 'display', lang: 'vi' },
  { id: "ja-new-tegomin", label: "New Tegomin", group: 'serif', lang: 'ja' },
  { id: "vn-nghich-thuy-han", label: "Nghich Thuy Han", group: 'sans', lang: 'vi' },
  { id: "ja-noto-sans-jp", label: "Noto Sans JP", group: 'sans', lang: 'ja' },
  { id: "ko-noto-sans-kr", label: "Noto Sans KR", group: 'sans', lang: 'ko' },
  { id: "ja-noto-serif-jp", label: "Noto Serif JP", group: 'serif', lang: 'ja' },
  { id: "ko-noto-serif-kr", label: "Noto Serif KR", group: 'serif', lang: 'ko' },
  { id: "vn-nova-square", label: "Nova Square", group: 'sans', lang: 'vi' },
  { id: "ko-orbit", label: "Orbit", group: 'sans', lang: 'ko' },
  { id: "vn-oregano", label: "Oregano", group: 'script', lang: 'vi' },
  { id: "vn-oswald", label: "Oswald", group: 'sans', lang: 'vi' },
  { id: "vn-pacifico", label: "Pacifico", group: 'script', lang: 'vi' },
  { id: "ja-palette-mosaic", label: "Palette Mosaic", group: 'display', lang: 'ja' },
  { id: "vn-palm-canyon-drive", label: "Palm Canyon Drive", group: 'script', lang: 'vi' },
  { id: "vn-paris-2024", label: "Paris 2024", group: 'display', lang: 'vi' },
  { id: "vn-philosopher", label: "Philosopher", group: 'sans', lang: 'vi' },
  { id: "vn-piklab-montra", label: "Piklab Montra", group: 'sans', lang: 'vi' },
  { id: "vn-playfair-display", label: "Playfair Display", group: 'serif', lang: 'vi' },
  { id: "vn-playful", label: "Playful", group: 'sans', lang: 'vi' },
  { id: "vn-plumage", label: "Plumage", group: 'script', lang: 'vi' },
  { id: "ko-poor-story", label: "Poor Story", group: 'display', lang: 'ko' },
  { id: "ja-potta-one", label: "Potta One", group: 'display', lang: 'ja' },
  { id: "vn-prata", label: "Prata", group: 'sans', lang: 'vi' },
  { id: "vn-protest-strike", label: "Protest Strike", group: 'sans', lang: 'vi' },
  { id: "vn-providence", label: "Providence", group: 'script', lang: 'vi' },
  { id: "vn-ps-anton", label: "PS Anton", group: 'sans', lang: 'vi' },
  { id: "vn-ps-bebas-neue", label: "PS Bebas Neue", group: 'sans', lang: 'vi' },
  { id: "vn-ps-big-shoulders", label: "PS Big Shoulders", group: 'sans', lang: 'vi' },
  { id: "vn-ps-bigger", label: "PS Bigger", group: 'sans', lang: 'vi' },
  { id: "vn-ps-bolden", label: "PS Bolden", group: 'sans', lang: 'vi' },
  { id: "vn-queen-of-silence", label: "Queen of Silence", group: 'display', lang: 'vi' },
  { id: "vn-questrial", label: "Questrial", group: 'sans', lang: 'vi' },
  { id: "vn-raleway", label: "Raleway", group: 'sans', lang: 'vi' },
  { id: "ja-rampart-one", label: "Rampart One", group: 'display', lang: 'ja' },
  { id: "vn-rancho", label: "Rancho", group: 'script', lang: 'vi' },
  { id: "vn-reggae-one", label: "Reggae One", group: 'display', lang: 'vi' },
  { id: "ja-reggae-one", label: "Reggae One", group: 'display', lang: 'ja' },
  { id: "vn-rochester", label: "Rochester", group: 'script', lang: 'vi' },
  { id: "ja-rock-3d", label: "Rock 3D", group: 'display', lang: 'ja' },
  { id: "ja-rocknroll-one", label: "RocknRoll One", group: 'sans', lang: 'ja' },
  { id: "vn-rose-gard", label: "Rose Gard", group: 'display', lang: 'vi' },
  { id: "vn-runholdy", label: "Runholdy", group: 'display', lang: 'vi' },
  { id: "vn-saga-arjuna", label: "Saga Arjuna", group: 'display', lang: 'vi' },
  { id: "vn-saira", label: "Saira", group: 'sans', lang: 'vi' },
  { id: "vn-sandraloka", label: "Sandraloka", group: 'sans', lang: 'vi' },
  { id: "vn-satisfy", label: "Satisfy", group: 'script', lang: 'vi' },
  { id: "ja-sawarabi-gothic", label: "Sawarabi Gothic", group: 'sans', lang: 'ja' },
  { id: "ja-sawarabi-mincho", label: "Sawarabi Mincho", group: 'serif', lang: 'ja' },
  { id: "vn-scaver", label: "Scaver", group: 'serif', lang: 'vi' },
  { id: "vn-shantay", label: "Shantay", group: 'script', lang: 'vi' },
  { id: "ja-shippori-antique", label: "Shippori Antique", group: 'sans', lang: 'ja' },
  { id: "ja-shippori-antique-b1", label: "Shippori Antique B1", group: 'sans', lang: 'ja' },
  { id: "ja-shippori-mincho", label: "Shippori Mincho", group: 'serif', lang: 'ja' },
  { id: "ja-shippori-mincho-b1", label: "Shippori Mincho B1", group: 'serif', lang: 'ja' },
  { id: "ja-shizuru", label: "Shizuru", group: 'display', lang: 'ja' },
  { id: "ko-single-day", label: "Single Day", group: 'display', lang: 'ko' },
  { id: "ja-slackside-one", label: "Slackside One", group: 'script', lang: 'ja' },
  { id: "vn-smile-delight", label: "Smile Delight", group: 'display', lang: 'vi' },
  { id: "ko-song-myung", label: "Song Myung", group: 'serif', lang: 'ko' },
  { id: "vn-sounds-analog", label: "Sounds Analog", group: 'display', lang: 'vi' },
  { id: "vn-splendid-script", label: "Splendid Script", group: 'script', lang: 'vi' },
  { id: "vn-stager", label: "Stager", group: 'serif', lang: 'vi' },
  { id: "vn-stardew-valley", label: "Stardew Valley", group: 'display', lang: 'vi' },
  { id: "ja-stick", label: "Stick", group: 'sans', lang: 'ja' },
  { id: "vn-storm-fighter", label: "Storm Fighter", group: 'display', lang: 'vi' },
  { id: "vn-streetbrush", label: "Streetbrush", group: 'script', lang: 'vi' },
  { id: "ko-stylish", label: "Stylish", group: 'sans', lang: 'ko' },
  { id: "vn-sue-ellen-francisco", label: "Sue Ellen Francisco", group: 'script', lang: 'vi' },
  { id: "ko-sunflower", label: "Sunflower", group: 'sans', lang: 'ko' },
  { id: "vn-svn-aaron-script", label: "SVN-Aaron Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-abril-fatface", label: "SVN-Abril Fatface", group: 'serif', lang: 'vi' },
  { id: "vn-svn-acherus", label: "SVN-Acherus", group: 'sans', lang: 'vi' },
  { id: "vn-svn-adam-gorry", label: "SVN-Adam Gorry", group: 'sans', lang: 'vi' },
  { id: "vn-svn-adeline", label: "SVN-Adeline", group: 'script', lang: 'vi' },
  { id: "vn-svn-agency-fb", label: "SVN-Agency FB", group: 'sans', lang: 'vi' },
  { id: "vn-svn-aguda", label: "SVN-Aguda", group: 'sans', lang: 'vi' },
  { id: "vn-svn-alek", label: "SVN-Alek", group: 'script', lang: 'vi' },
  { id: "vn-svn-aleo", label: "SVN-Aleo", group: 'serif', lang: 'vi' },
  { id: "vn-svn-aller", label: "SVN-Aller", group: 'sans', lang: 'vi' },
  { id: "vn-svn-amethyst", label: "SVN-Amethyst", group: 'script', lang: 'vi' },
  { id: "vn-svn-amperzand", label: "SVN-Amperzand", group: 'serif', lang: 'vi' },
  { id: "vn-svn-amsdam", label: "SVN-Amsdam", group: 'sans', lang: 'vi' },
  { id: "vn-svn-amsi-cond", label: "SVN-Amsi Cond", group: 'sans', lang: 'vi' },
  { id: "vn-svn-amsi-narw", label: "SVN-Amsi Narw", group: 'sans', lang: 'vi' },
  { id: "vn-svn-anastasia", label: "SVN-Anastasia", group: 'script', lang: 'vi' },
  { id: "vn-svn-androgyne", label: "SVN-Androgyne", group: 'sans', lang: 'vi' },
  { id: "vn-svn-angellife", label: "SVN-Angellife", group: 'script', lang: 'vi' },
  { id: "vn-svn-angely", label: "SVN-Angely", group: 'script', lang: 'vi' },
  { id: "vn-svn-anthem", label: "SVN-Anthem", group: 'script', lang: 'vi' },
  { id: "vn-svn-apple", label: "SVN-Apple", group: 'display', lang: 'vi' },
  { id: "vn-svn-appleberry", label: "SVN-Appleberry", group: 'display', lang: 'vi' },
  { id: "vn-svn-aptima", label: "SVN-Aptima", group: 'sans', lang: 'vi' },
  { id: "vn-svn-arch", label: "SVN-Arch", group: 'sans', lang: 'vi' },
  { id: "vn-svn-archaic-1897", label: "SVN-Archaic 1897", group: 'serif', lang: 'vi' },
  { id: "vn-svn-arco-typography", label: "SVN-ARCO Typography", group: 'display', lang: 'vi' },
  { id: "vn-svn-arial", label: "SVN-Arial", group: 'sans', lang: 'vi' },
  { id: "vn-svn-aslang-barry", label: "SVN-Aslang Barry", group: 'script', lang: 'vi' },
  { id: "vn-svn-astronout", label: "SVN-Astronout", group: 'script', lang: 'vi' },
  { id: "vn-svn-athena", label: "SVN-Athena", group: 'serif', lang: 'vi' },
  { id: "vn-svn-avaline-script", label: "SVN-Avaline Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-avengeance", label: "SVN-Avengeance", group: 'display', lang: 'vi' },
  { id: "vn-svn-avo", label: "SVN-Avo", group: 'sans', lang: 'vi' },
  { id: "vn-svn-az-cupcakes", label: "SVN-AZ Cupcakes", group: 'script', lang: 'vi' },
  { id: "vn-svn-bali-script", label: "SVN-Bali Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-balladeer-light", label: "SVN-Balladeer Light", group: 'script', lang: 'vi' },
  { id: "vn-svn-ballarea-typeface", label: "SVN-Ballarea Typeface", group: 'script', lang: 'vi' },
  { id: "vn-svn-banana-chip-muffins", label: "SVN-Banana Chip Muffins", group: 'display', lang: 'vi' },
  { id: "vn-svn-bango", label: "SVN-Bango", group: 'display', lang: 'vi' },
  { id: "vn-svn-bariol", label: "SVN-Bariol", group: 'sans', lang: 'vi' },
  { id: "vn-svn-batman-forever-alternate", label: "SVN-Batman Forever Alternate", group: 'display', lang: 'vi' },
  { id: "vn-svn-bear", label: "SVN-Bear", group: 'serif', lang: 'vi' },
  { id: "vn-svn-beast", label: "SVN-Beast", group: 'sans', lang: 'vi' },
  { id: "vn-svn-beauty-atok-script", label: "SVN-Beauty Atok Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-bellico", label: "SVN-Bellico", group: 'script', lang: 'vi' },
  { id: "vn-svn-bellwethers", label: "SVN-Bellwethers", group: 'script', lang: 'vi' },
  { id: "vn-svn-beloved", label: "SVN-Beloved", group: 'script', lang: 'vi' },
  { id: "vn-svn-berkshire-swash", label: "SVN-Berkshire Swash", group: 'serif', lang: 'vi' },
  { id: "vn-svn-billo", label: "SVN-Billo", group: 'display', lang: 'vi' },
  { id: "vn-svn-billy", label: "SVN-Billy", group: 'display', lang: 'vi' },
  { id: "vn-svn-bio-sans", label: "SVN-Bio Sans", group: 'sans', lang: 'vi' },
  { id: "vn-svn-bira", label: "SVN-Bira", group: 'script', lang: 'vi' },
  { id: "vn-svn-birth-of-a-hero", label: "SVN-Birth Of A Hero", group: 'display', lang: 'vi' },
  { id: "vn-svn-bistro-script", label: "SVN-Bistro Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-black-diamond", label: "SVN-Black Diamond", group: 'script', lang: 'vi' },
  { id: "vn-svn-blade-runner", label: "SVN-Blade Runner", group: 'display', lang: 'vi' },
  { id: "vn-svn-blenda-script", label: "SVN-Blenda Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-block", label: "SVN-Block", group: 'display', lang: 'vi' },
  { id: "vn-svn-blog-script", label: "SVN-Blog Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-blow-brush", label: "SVN-Blow Brush", group: 'display', lang: 'vi' },
  { id: "vn-svn-blue", label: "SVN-Blue", group: 'sans', lang: 'vi' },
  { id: "vn-svn-book-antiqua", label: "SVN-Book Antiqua", group: 'serif', lang: 'vi' },
  { id: "vn-svn-bradley-hand", label: "SVN-Bradley Hand", group: 'script', lang: 'vi' },
  { id: "vn-svn-bree", label: "SVN-Bree", group: 'sans', lang: 'vi' },
  { id: "vn-svn-brother-1816", label: "SVN-Brother 1816", group: 'sans', lang: 'vi' },
  { id: "vn-svn-brunette", label: "SVN-Brunette", group: 'script', lang: 'vi' },
  { id: "vn-svn-bruselo-script", label: "SVN-Bruselo Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-bulgary", label: "SVN-Bulgary", group: 'script', lang: 'vi' },
  { id: "vn-svn-cafe-lounge-19", label: "SVN-Cafe Lounge 19", group: 'display', lang: 'vi' },
  { id: "vn-svn-calama", label: "SVN-Calama", group: 'sans', lang: 'vi' },
  { id: "vn-svn-calling-code", label: "SVN-Calling Code", group: 'sans', lang: 'vi' },
  { id: "vn-svn-candy-script", label: "SVN-Candy Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-caprica-script", label: "SVN-Caprica Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-carington", label: "SVN-Carington", group: 'script', lang: 'vi' },
  { id: "vn-svn-cattleya-script", label: "SVN-Cattleya Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-channel", label: "SVN-Channel", group: 'script', lang: 'vi' },
  { id: "vn-svn-cheeky-rabbit", label: "SVN-Cheeky Rabbit", group: 'display', lang: 'vi' },
  { id: "vn-svn-cherryla", label: "SVN-Cherryla", group: 'script', lang: 'vi' },
  { id: "vn-svn-ciao-bella", label: "SVN-Ciao Bella", group: 'script', lang: 'vi' },
  { id: "vn-svn-cinnamoncake", label: "SVN-Cinnamoncake", group: 'display', lang: 'vi' },
  { id: "vn-svn-cintra", label: "SVN-Cintra", group: 'sans', lang: 'vi' },
  { id: "vn-svn-clementine", label: "SVN-Clementine", group: 'display', lang: 'vi' },
  { id: "vn-svn-coco-fy", label: "SVN-Coco FY", group: 'script', lang: 'vi' },
  { id: "vn-svn-comic-sans-ms", label: "SVN-Comic Sans MS", group: 'sans', lang: 'vi' },
  { id: "vn-svn-cookie", label: "SVN-Cookie", group: 'script', lang: 'vi' },
  { id: "vn-svn-cookies", label: "SVN-Cookies", group: 'display', lang: 'vi' },
  { id: "vn-svn-corki", label: "SVN-Corki", group: 'serif', lang: 'vi' },
  { id: "vn-svn-d-sari", label: "SVN-D Sari", group: 'sans', lang: 'vi' },
  { id: "vn-svn-daisy", label: "SVN-Daisy", group: 'script', lang: 'vi' },
  { id: "vn-svn-dancing-script", label: "SVN-Dancing Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-darleston", label: "SVN-Darleston", group: 'script', lang: 'vi' },
  { id: "vn-svn-days", label: "SVN-Days", group: 'sans', lang: 'vi' },
  { id: "vn-svn-deadhead-script", label: "SVN-Deadhead Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-delabasto", label: "SVN-Delabasto", group: 'display', lang: 'vi' },
  { id: "vn-svn-desire", label: "SVN-Desire", group: 'display', lang: 'vi' },
  { id: "vn-svn-dessert-menu-script", label: "SVN-Dessert Menu Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-digitalis", label: "SVN-Digitalis", group: 'sans', lang: 'vi' },
  { id: "vn-svn-dk-clochard", label: "SVN-DK Clochard", group: 'display', lang: 'vi' },
  { id: "vn-svn-doodly", label: "SVN-Doodly", group: 'display', lang: 'vi' },
  { id: "vn-svn-dumpling", label: "SVN-Dumpling", group: 'display', lang: 'vi' },
  { id: "vn-svn-effra", label: "SVN-Effra", group: 'sans', lang: 'vi' },
  { id: "vn-svn-egregio-script", label: "SVN-Egregio Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-elle-novac-extra-light", label: "SVN-Elle NovaC Extra Light", group: 'sans', lang: 'vi' },
  { id: "vn-svn-endless-sorrow", label: "SVN-Endless Sorrow", group: 'display', lang: 'vi' },
  { id: "vn-svn-every-movie-every-night", label: "SVN-Every Movie Every Night", group: 'sans', lang: 'vi' },
  { id: "vn-svn-fadilla", label: "SVN-Fadilla", group: 'script', lang: 'vi' },
  { id: "vn-svn-fashion", label: "SVN-Fashion", group: 'display', lang: 'vi' },
  { id: "vn-svn-fff-tusj", label: "SVN-FFF Tusj", group: 'display', lang: 'vi' },
  { id: "vn-svn-fiolex-girls", label: "SVN-Fiolex Girls", group: 'script', lang: 'vi' },
  { id: "vn-svn-fjalla-one", label: "SVN-Fjalla One", group: 'sans', lang: 'vi' },
  { id: "vn-svn-flamingo-script", label: "SVN-Flamingo Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-fourth", label: "SVN-Fourth", group: 'script', lang: 'vi' },
  { id: "vn-svn-franko", label: "SVN-Franko", group: 'sans', lang: 'vi' },
  { id: "vn-svn-freestyle", label: "SVN-Freestyle", group: 'script', lang: 'vi' },
  { id: "vn-svn-genica-pro", label: "SVN-Genica Pro", group: 'serif', lang: 'vi' },
  { id: "vn-svn-georgia", label: "SVN-Georgia", group: 'serif', lang: 'vi' },
  { id: "vn-svn-gidry", label: "SVN-Gidry", group: 'script', lang: 'vi' },
  { id: "vn-svn-gilroy", label: "SVN-Gilroy", group: 'sans', lang: 'vi' },
  { id: "vn-svn-good-dog", label: "SVN-Good Dog", group: 'display', lang: 'vi' },
  { id: "vn-svn-gotham", label: "SVN-Gotham", group: 'sans', lang: 'vi' },
  { id: "vn-svn-gotham-rounded", label: "SVN-Gotham Rounded", group: 'sans', lang: 'vi' },
  { id: "vn-svn-gretoon", label: "SVN-Gretoon", group: 'display', lang: 'vi' },
  { id: "vn-svn-grocery-rounded", label: "SVN-Grocery Rounded", group: 'sans', lang: 'vi' },
  { id: "vn-svn-guerrilla", label: "SVN-Guerrilla", group: 'display', lang: 'vi' },
  { id: "vn-svn-hand-gothic", label: "SVN-Hand Gothic", group: 'sans', lang: 'vi' },
  { id: "vn-svn-haptic-script", label: "SVN-Haptic Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-harabaras", label: "SVN-Harabaras", group: 'sans', lang: 'vi' },
  { id: "vn-svn-harman-script", label: "SVN-Harman Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-heathergreen", label: "SVN-Heathergreen", group: 'sans', lang: 'vi' },
  { id: "vn-svn-helga", label: "SVN-Helga", group: 'script', lang: 'vi' },
  { id: "vn-svn-helves", label: "SVN-Helves", group: 'sans', lang: 'vi' },
  { id: "vn-svn-helvetica-neue", label: "SVN-Helvetica Neue", group: 'sans', lang: 'vi' },
  { id: "vn-svn-helvetica-neue-heavy", label: "SVN-Helvetica Neue Heavy", group: 'sans', lang: 'vi' },
  { id: "vn-svn-helvetica-neue-light", label: "SVN-Helvetica Neue Light", group: 'sans', lang: 'vi' },
  { id: "vn-svn-hemi-head", label: "SVN-Hemi Head", group: 'sans', lang: 'vi' },
  { id: "vn-svn-heroe-pro", label: "SVN-Heroe Pro", group: 'serif', lang: 'vi' },
  { id: "vn-svn-hole-hearted", label: "SVN-Hole Hearted", group: 'display', lang: 'vi' },
  { id: "vn-svn-holidays", label: "SVN-Holidays", group: 'script', lang: 'vi' },
  { id: "vn-svn-hollie-script-pro", label: "SVN-Hollie Script Pro", group: 'script', lang: 'vi' },
  { id: "vn-svn-hollycakes", label: "SVN-Hollycakes", group: 'script', lang: 'vi' },
  { id: "vn-svn-indie", label: "SVN-Indie", group: 'script', lang: 'vi' },
  { id: "vn-svn-internation", label: "SVN-Internation", group: 'sans', lang: 'vi' },
  { id: "vn-svn-jonesy-script", label: "SVN-Jonesy Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-justice-league", label: "SVN-Justice League", group: 'sans', lang: 'vi' },
  { id: "vn-svn-karlita", label: "SVN-Karlita", group: 'script', lang: 'vi' },
  { id: "vn-svn-kelson-sans", label: "SVN-Kelson Sans", group: 'sans', lang: 'vi' },
  { id: "vn-svn-kg-ten-thousand-reasons", label: "SVN-KG Ten Thousand Reasons", group: 'script', lang: 'vi' },
  { id: "vn-svn-kimberley", label: "SVN-Kimberley", group: 'sans', lang: 'vi' },
  { id: "vn-svn-kitten", label: "SVN-Kitten", group: 'script', lang: 'vi' },
  { id: "vn-svn-larch-shaded", label: "SVN-Larch Shaded", group: 'script', lang: 'vi' },
  { id: "vn-svn-linux-libertine", label: "SVN-Linux Libertine", group: 'serif', lang: 'vi' },
  { id: "vn-svn-lobster", label: "SVN-Lobster", group: 'script', lang: 'vi' },
  { id: "vn-svn-lolapeluza-black", label: "SVN-Lolapeluza Black", group: 'display', lang: 'vi' },
  { id: "vn-svn-madre-script", label: "SVN-Madre Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-manus", label: "SVN-Manus", group: 'script', lang: 'vi' },
  { id: "vn-svn-maphylla", label: "SVN-Maphylla", group: 'script', lang: 'vi' },
  { id: "vn-svn-marpesia-pro", label: "SVN-Marpesia Pro", group: 'script', lang: 'vi' },
  { id: "vn-svn-marujo", label: "SVN-Marujo", group: 'display', lang: 'vi' },
  { id: "vn-svn-mercury-script", label: "SVN-Mercury Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-merge", label: "SVN-Merge", group: 'sans', lang: 'vi' },
  { id: "vn-svn-mikado", label: "SVN-Mikado", group: 'sans', lang: 'vi' },
  { id: "vn-svn-miller-banner", label: "SVN-Miller Banner", group: 'serif', lang: 'vi' },
  { id: "vn-svn-momento", label: "SVN-Momento", group: 'display', lang: 'vi' },
  { id: "vn-svn-monday", label: "SVN-Monday", group: 'script', lang: 'vi' },
  { id: "vn-svn-moon-star", label: "SVN-Moon star", group: 'display', lang: 'vi' },
  { id: "vn-svn-morva", label: "SVN-MORVA", group: 'serif', lang: 'vi' },
  { id: "vn-svn-motion-picture", label: "SVN-Motion Picture", group: 'script', lang: 'vi' },
  { id: "vn-svn-mutlu", label: "SVN-Mutlu", group: 'script', lang: 'vi' },
  { id: "vn-svn-neogrey", label: "SVN-Neogrey", group: 'sans', lang: 'vi' },
  { id: "vn-svn-neusa", label: "SVN-Neusa", group: 'sans', lang: 'vi' },
  { id: "vn-svn-neutraface-2", label: "SVN-Neutraface 2", group: 'sans', lang: 'vi' },
  { id: "vn-svn-new-athletic-m54", label: "SVN-New Athletic M54", group: 'display', lang: 'vi' },
  { id: "vn-svn-newton", label: "SVN-Newton", group: 'serif', lang: 'vi' },
  { id: "vn-svn-nexa-light", label: "SVN-Nexa Light", group: 'sans', lang: 'vi' },
  { id: "vn-svn-passion", label: "SVN-Passion", group: 'display', lang: 'vi' },
  { id: "vn-svn-pf-din-text-pro", label: "SVN-PF Din Text Pro", group: 'sans', lang: 'vi' },
  { id: "vn-svn-poky-s", label: "SVN-Poky's", group: 'display', lang: 'vi' },
  { id: "vn-svn-poppins", label: "SVN-Poppins", group: 'sans', lang: 'vi' },
  { id: "vn-svn-posterizer-kg-inline", label: "SVN-Posterizer KG Inline", group: 'display', lang: 'vi' },
  { id: "vn-svn-prima", label: "SVN-Prima", group: 'display', lang: 'vi' },
  { id: "vn-svn-product-sans", label: "SVN-Product Sans", group: 'sans', lang: 'vi' },
  { id: "vn-svn-pyes-pa-headline", label: "SVN-Pyes Pa Headline", group: 'serif', lang: 'vi' },
  { id: "vn-svn-ready", label: "SVN-Ready", group: 'display', lang: 'vi' },
  { id: "vn-svn-redressed", label: "SVN-Redressed", group: 'script', lang: 'vi' },
  { id: "vn-svn-reklame-script", label: "SVN-Reklame Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-reliant", label: "SVN-Reliant", group: 'script', lang: 'vi' },
  { id: "vn-svn-revolution", label: "SVN-Revolution", group: 'display', lang: 'vi' },
  { id: "vn-svn-rex", label: "SVN-Rex", group: 'sans', lang: 'vi' },
  { id: "vn-svn-ridemybike-pro", label: "SVN-RidemyBike Pro", group: 'sans', lang: 'vi' },
  { id: "vn-svn-riesling", label: "SVN-Riesling", group: 'display', lang: 'vi' },
  { id: "vn-svn-ringdena", label: "SVN-Ringdena", group: 'script', lang: 'vi' },
  { id: "vn-svn-rio-2016", label: "SVN-Rio 2016", group: 'display', lang: 'vi' },
  { id: "vn-svn-rocker", label: "SVN-Rocker", group: 'display', lang: 'vi' },
  { id: "vn-svn-rosalinda", label: "SVN-Rosalinda", group: 'script', lang: 'vi' },
  { id: "vn-svn-roselina-script", label: "SVN-Roselina Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-rounded", label: "SVN-Rounded", group: 'sans', lang: 'vi' },
  { id: "vn-svn-russell", label: "SVN-Russell", group: 'sans', lang: 'vi' },
  { id: "vn-svn-saf", label: "SVN-SAF", group: 'sans', lang: 'vi' },
  { id: "vn-svn-safina-script", label: "SVN-Safina Script", group: 'script', lang: 'vi' },
  { id: "vn-svn-saldina", label: "SVN-Saldina", group: 'script', lang: 'vi' },
  { id: "vn-sweet-peachy", label: "Sweet Peachy", group: 'sans', lang: 'vi' },
  { id: "vn-symphony-pro", label: "Symphony Pro", group: 'script', lang: 'vi' },
  { id: "vn-tan-jambore", label: "TAN Jambore", group: 'sans', lang: 'vi' },
  { id: "vn-thang", label: "Thang", group: 'script', lang: 'vi' },
  { id: "vn-the-nautigal", label: "The Nautigal", group: 'script', lang: 'vi' },
  { id: "vn-thegora", label: "Thegora", group: 'sans', lang: 'vi' },
  { id: "vn-tnh-xuong", label: "TNH Xuong", group: 'display', lang: 'vi' },
  { id: "ja-train-one", label: "Train One", group: 'display', lang: 'ja' },
  { id: "vn-tratexvit", label: "TratexVit", group: 'sans', lang: 'vi' },
  { id: "ja-tsukimi-rounded", label: "Tsukimi Rounded", group: 'sans', lang: 'ja' },
  { id: "vn-ubuntu", label: "Ubuntu", group: 'sans', lang: 'vi' },
  { id: "vn-verlag", label: "Verlag", group: 'sans', lang: 'vi' },
  { id: "vn-vermin-verile", label: "Vermin Verile", group: 'display', lang: 'vi' },
  { id: "vn-vintage-goods", label: "Vintage Goods", group: 'script', lang: 'vi' },
  { id: "vn-virlyn", label: "Virlyn", group: 'display', lang: 'vi' },
  { id: "vn-viva-la-fiesta-uno-base", label: "Viva La Fiesta - Uno Base", group: 'display', lang: 'vi' },
  { id: "vn-vl-angelline", label: "VL Angelline", group: 'script', lang: 'vi' },
  { id: "vn-vl-selfie", label: "VL Selfie", group: 'script', lang: 'vi' },
  { id: "vn-vnm-sans-std", label: "VNM Sans Std", group: 'sans', lang: 'vi' },
  { id: "ja-wdxl-lubrifont-jp-n", label: "WDXL Lubrifont JP N", group: 'sans', lang: 'ja' },
  { id: "vn-wind-script", label: "Wind Script", group: 'script', lang: 'vi' },
  { id: "vn-winstgue", label: "Winstgue", group: 'display', lang: 'vi' },
  { id: "ko-yeon-sung", label: "Yeon Sung", group: 'display', lang: 'ko' },
  { id: "ja-yomogi", label: "Yomogi", group: 'script', lang: 'ja' },
  { id: "vn-young", label: "Young", group: 'sans', lang: 'vi' },
  { id: "vn-young-display", label: "Young Display", group: 'sans', lang: 'vi' },
  { id: "ja-yuji-boku", label: "Yuji Boku", group: 'serif', lang: 'ja' },
  { id: "ja-yuji-mai", label: "Yuji Mai", group: 'serif', lang: 'ja' },
  { id: "ja-yuji-syuku", label: "Yuji Syuku", group: 'serif', lang: 'ja' },
  { id: "ja-yusei-magic", label: "Yusei Magic", group: 'sans', lang: 'ja' },
  { id: "ja-zen-antique", label: "Zen Antique", group: 'serif', lang: 'ja' },
  { id: "ja-zen-antique-soft", label: "Zen Antique Soft", group: 'serif', lang: 'ja' },
  { id: "ja-zen-kaku-gothic-antique", label: "Zen Kaku Gothic Antique", group: 'sans', lang: 'ja' },
  { id: "ja-zen-kaku-gothic-new", label: "Zen Kaku Gothic New", group: 'sans', lang: 'ja' },
  { id: "ja-zen-kurenaido", label: "Zen Kurenaido", group: 'sans', lang: 'ja' },
  { id: "ja-zen-maru-gothic", label: "Zen Maru Gothic", group: 'sans', lang: 'ja' },
  { id: "ja-zen-old-mincho", label: "Zen Old Mincho", group: 'serif', lang: 'ja' },
]
